name: 🚀 Deploy NestJS Bcd ..log Backend API to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        source: "."
        target: "/root/quistial_dilan/resultados-deportivos-backend"

    - name: Run deploy commands on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd cd /root/quistial_dilan/resultados-deportivos-backend
          echo "$${{ secrets.ENV_FILE }}" > .env
          npm install
          npm run build
          pm2 restart resultados-deportivos-backend-api || pm2 start dist/main.js --name resultados-deportivos-backend-api